### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by rumblyelk**
Implementing the basics, such as Addresses, Nodes, etc.

### CODE REVIEW

**Review by DeedleFake — CHANGES_REQUESTED** [review]
Getting there, but definitely needs a bit of work still. The usage of random bytes instead of actual keys in particular makes the addresses not particularly useful.

**Review by rumblyelk — COMMENTED** [review]
Took care of the changes.

**Comment by rumblyelk** [comment]
@DeedleFake I'm pretty certain this is ready to merge into `main`. Thoughts?

**Review by DeedleFake — APPROVED** [review]
LGTM.

**Pull request merged**
